name: 'air_project_london'
version: '1.0.0'
config-version: 2

profile: 'air_project_london'

model-paths: ["models"]
seed-paths: ["seeds"]
test-paths: ["tests"]
analysis-paths: ["analyses"]
macro-paths: ["macros"]
snapshot-paths: ["snapshots"]

target-path: "target"  
clean-targets:         
  - "target"
  - "dbt_packages"

models:
  air_project_london:
    +materialized: view