air_project_london:
  target: dev
  outputs:
    dev:
      type: postgres
      host: db             # Name of the docker service 
      user: "{{ env_var('DB_USER') }}"
      password: "{{ env_var('DB_PASS') }}"
      port: 5432
      dbname: "{{ env_var('DB_NAME') }}"
      schema: public
      threads: 1