air_project_london:
  target: dev
  outputs:
    dev:
      type: postgres
      host: db
      # Names in .env
      user: "{{ env_var('POSTGRES_USER') }}"
      password: "{{ env_var('POSTGRES_PASSWORD') }}"
      port: 5432
      dbname: "{{ env_var('POSTGRES_DB') }}"
      schema: public
      threads: 1