config:
  send_anonymous_usage_stats: False

air_project_london: # Name of the dbt project
  outputs:
    dev:
      type: postgres
      host: db
      user: "{{ env_var('DB_USER') }}"
      password: "{{ env_var('DB_PASS') }}"
      port: 5432
      dbname: "{{ env_var('DB_NAME') }}"
      schema: public
      threads: 1
  target: dev