FROM grafana/grafana-oss:latest

# Switching to root privileges avoids permission issues when installing plugins.
USER root

# # Install the maps plugin
RUN grafana-cli plugins install grafana-worldmap-panel

# For security reasons, the default Grafana user is reverted to.
USER grafana

# The provisioning configuration is copied (although the docker-compose volume takes precedence over this)
COPY ./provisioning /etc/grafana/provisioning

# http://localhost:3000 